### ISSUE TITLE
Multiple instances of buildbox

### ISSUE THREAD

**Issue by tarragon** [buildbox/agent#19]
Hi,

I encountered a situation where I inadvertently started up two copies of the buildbox-agent on the same system, using the same access token. Both appeared to be able to start builds, and there was of course a high potential to conflict if they built the same project.

It would be good if a second agent using an access token that's currently in use by another agent would get rejected.

It would also be good if the log file output would note the PID so this situation can be spotted easily while tailing logs.

**Comment by keithpitt** [comment]
Just closing this because it's fixed in the new agents. If this issue is still affecting you, let me know, and I'll switch on the new agents for you! :dancers:
